# Prometheus global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (uncomment and configure if needed)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files (uncomment and add your rule files if needed)
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "node_exporter"
    static_configs:
      - targets: ["<VPS_IP>:9100"]
